import {createRequire} from 'node:module';import {gzipSync} from 'node:zlib';import {createHash} from 'node:crypto';
import {afterEach,expect,it} from 'vitest';import {initializeCloudflareV1,uploadCloudflareV1} from './cloudflare-v1-upload';import type{SqlStore}from './cloudflare-store';
const {DatabaseSync}=createRequire(import.meta.url)('node:sqlite');const databases:Array<{close():void}>=[];afterEach(()=>databases.splice(0).forEach(d=>d.close()));
function store(){const db=new DatabaseSync(':memory:');databases.push(db);const sql:SqlStore={exec:(q,...args)=>{const rows=db.prepare(q).all(...args);return{toArray:()=>rows};}};initializeCloudflareV1(sql);return {sql,transactionSync<T>(f:()=>T):T{db.exec('BEGIN');try{const r=f();db.exec('COMMIT');return r;}catch(e){db.exec('ROLLBACK');throw e;}}};}
function snapshot(time=new Date().toISOString()){return{schema_version:1,collected_at:time,host:{cpu_percent:1,ram_used_bytes:1,ram_total_bytes:2,disk_used_bytes:1,disk_total_bytes:2,load_1m:1,load_5m:1,load_15m:1,uptime_seconds:1},services:[],containers:[]};}
function request(name:string,payload:unknown,generation?:string){return new Request('https://example.test/__collector/'+name,{method:'PUT',headers:generation?{'X-Frontpage-Generation':generation}:{},body:gzipSync(JSON.stringify(payload))});}
it('rejects invalid schemas, replay, future dates and bounded decompression without replacing last good',async()=>{const s=store(),first=snapshot();expect((await uploadCloudflareV1(request('latest.json',first),s,'latest.json')).status).toBe(204);const before=s.sql.exec('SELECT data FROM metrics_snapshot').toArray();for(const p of [{},snapshot('2020-01-01T00:00:00Z'),snapshot('2099-01-01T00:00:00Z')])expect((await uploadCloudflareV1(request('latest.json',p),s,'latest.json')).status).toBe(400);expect(s.sql.exec('SELECT data FROM metrics_snapshot').toArray()).toEqual(before);
 expect((await uploadCloudflareV1(new Request('https://example.test',{method:'PUT',body:gzipSync(Buffer.alloc(512*1024+1))}),s,'latest.json')).status).toBe(413);
 let cancelled=false;const body=new ReadableStream<Uint8Array>({pull(c){c.enqueue(new Uint8Array(600*1024));},cancel(){cancelled=true;}});const init:RequestInit&{duplex:'half'}={method:'PUT',body,duplex:'half'};expect((await uploadCloudflareV1(new Request('https://example.test',init),s,'latest.json')).status).toBe(413);expect(cancelled).toBe(true);
});
it('activates only complete matched generations and commits idempotently',async()=>{const s=store(),latest=snapshot(),history={schema_version:1,samples:[latest]};const generation=createHash('sha256').update(JSON.stringify(latest)).update('\0').update(JSON.stringify(history)).digest('hex');
 expect((await uploadCloudflareV1(request('latest.json',latest,generation),s,'latest.json')).status).toBe(204);expect(s.sql.exec('SELECT * FROM metrics_v1_active').toArray()).toHaveLength(0);
 const commit=()=>uploadCloudflareV1(new Request('https://example.test',{method:'PUT',headers:{'X-Frontpage-Generation':generation}}),s,'v1/commit');expect((await commit()).status).toBe(400);
 expect((await uploadCloudflareV1(request('history.json',history,generation),s,'history.json')).status).toBe(204);expect((await commit()).status).toBe(204);expect((await commit()).status).toBe(204);expect(s.sql.exec('SELECT generation FROM metrics_v1_active').toArray()[0].generation).toBe(generation);
 expect((await uploadCloudflareV1(request('latest.json',snapshot()),s,'latest.json')).status).toBe(409);
});
